export type Language = 'en' | 'fr' | 'ar' | 'es';
export type ReadingMode = 'solo' | 'compare' | 'triangle' | 'circle';
export type Framework = 'attachment' | 'loveLanguages' | 'sociometry' | 'colorWheel' | 'intuition' | 'mixed';
export type ModuleType = 'multi' | 'solo';
/**
 * How a module's result is scored + rendered. Lets the engine + result screen branch on
 * intent rather than just `type`:
 * - `multi`       — pick-a-person, highest scorer wins (who_loves_me…).
 * - `valence`     — solo ±score total → positive/neutral/negative (am_i_problem).
 * - `count`       — solo "N of 20 signs present" (a relationship module read solo).
 * - `categorical` — solo, answers tagged to categories; winning category + a secondary
 *                   "edge" (attachment_style, aura_reading).
 */
export type ResultKind = 'valence' | 'count' | 'categorical' | 'multi';
export type ThemeId = 'cosmic' | 'desertOracle';

export interface LocalizedString {
  en: string;
  fr: string;
  ar: string;
  es: string;
}

export interface SoloAnswer {
  label: LocalizedString;
  score: number; // -2 | -1 | 1 | 2 (valence/count modules)
  /** For `categorical` modules: the category this answer points to (e.g. 'secure',
   *  'anxious', or an aura colour like 'red'). Ignored by valence/count scoring. */
  category?: string;
  /** Optional weight for a categorical answer's contribution (defaults to 1). */
  weight?: number;
}

export interface Question {
  id: string;
  text: LocalizedString;
  /**
   * Statement form of a multi question for solo mode ("{name} cools a tense
   * moment just by being there."), answered with the generic frequency scale.
   * `{name}` is replaced with the person's name. Falls back to `text` when absent.
   */
  soloText?: LocalizedString;
  framework: Framework;
  dimension: string;
  personWeight?: number; // for multi-person questions, default 1
  soloAnswers?: SoloAnswer[]; // for solo questions, always exactly 4 options
}

export interface Person {
  id: string;
  name: string;
  color: string; // hex
}

export interface ResultData {
  moduleId: string;
  mode: ReadingMode;
  winner?: Person;
  /** Multi tie: ids of ALL persons sharing the max score (2+ entries), or [] for a
   *  clear winner. `winner` still holds the first max scorer for backward compat —
   *  rendering must gate on this, never on `winner` alone. Absent on readings
   *  persisted before ties shipped (treat as []). */
  tiedWinnerIds?: string[];
  /** The tied Persons themselves (names + colors for the reveal, verdict and share
   *  card) — carried on the result so History reopens don't depend on session state. */
  tiedWinners?: Person[];
  verdict?: 'positive' | 'neutral' | 'negative';
  scores: Record<string, number>; // personId -> score (multi/solo) or category -> tally (categorical)
  dominantDimension: string;
  /** For `categorical` results: the runner-up category ("…with an Anxious edge"). */
  secondaryDimension?: string;
  /** For `count` results (a relationship module read solo): how many of the total
   *  questions registered a "sign present", surfaced as "N of {signalTotal} signs present". */
  signalCount?: number;
  signalTotal?: number;
  /** TRUE only when the result was generated by generateCountResult (a MIGRATED multi
   *  module read solo). Necessary because signalCount/signalTotal are set for EVERY multi
   *  module read solo — including ones that still fall back to the winner-race
   *  generateMultiResult — so they alone can't tell the two apart at render time. */
  isCountResult?: boolean;
  confidence: number; // clamped per scoring path (see scoringEngine)
  insights: LocalizedString[];
  /** Multi only: the winner template minus the name ("loves you the most.") — the
   *  subtitle under the reveal name. Derived per-locale from the RAW winnerTemplate at
   *  generation time, so it stays correct in locales where the name sits mid-sentence
   *  (render-time name-stripping of insights[0] did not). Absent on ties (insights[0]
   *  IS the tie verdict) and on readings persisted before this shipped (the result
   *  screen falls back to the legacy strip). */
  verdictLine?: LocalizedString;
  /** Punchy social-card quote picked at generation time (the dimension/verdict
   *  shareLine — see MultiResults/SoloResults.shareLines). Optional: readings
   *  persisted before the share card shipped don't carry one. */
  shareLine?: LocalizedString;
  attachmentLabel?: LocalizedString;
  loveLanguageLabel?: LocalizedString;
}

export interface Reading {
  id: string;
  moduleId: string;
  mode: ReadingMode;
  persons: Person[];
  answers: Record<string, string>; // questionId -> personId or answer index
  result: ResultData;
  createdAt: number; // unix timestamp
}

export interface Module {
  id: string;
  type: ModuleType;
  /** How the result is scored/rendered. Defaults to `type` ('multi' | a solo kind) when
   *  unset; set explicitly to 'categorical' / 'count' for the non-valence solo modules. */
  resultKind?: ResultKind;
  starsCost: Record<ReadingMode, number>;
  icon: string; // emoji
  color: string; // accent hex for glow
  framework: Framework;
  /** Placeholder module shown on Home as a dimmed "Coming soon" card (not playable). */
  comingSoon?: boolean;
  /** Star cost to permanently unlock a paid, buyable module. When set AND the id is not in
   *  `userStore.unlockedModules`, the module is locked-but-buyable: Home renders full-colour
   *  art + a ★cost pill, and entering the flow gates through `ModuleUnlockDialog`. Once
   *  unlocked it plays like any module (normal per-reading star costs apply). Absent = a free
   *  module with no unlock gate. */
  unlockCost?: number;
}

export interface ThemeColors {
  id: ThemeId;
  background: string;
  bg2: string;
  surface: string;
  surfaceBorder: string;
  borderStrong: string;
  primary: string;
  gradient: [string, string, string];
  /** The ambient screen-field gradient (top → mid → bottom) painted behind the
   *  navigator and mirrored inline by full-bleed screens. */
  fieldGradient: [string, string, string];
  text: string;
  textMuted: string;
  textDim: string;
  gold: string;
  rose: string;
  emerald: string;
  glow: string;
}

export interface MultiResults {
  winnerTemplate: LocalizedString;
  /** Tie verdict — used instead of winnerTemplate when 2+ persons share the max
   *  score. {names} is replaced with the tied names joined naturally per locale
   *  ("X and Y" / "X, Y, and Z" — see joinNames in scoringEngine). */
  tieTemplate: LocalizedString;
  insights: Record<string, LocalizedString[]>;
  /** One designed share-card quote per dimension (same keys as `insights`) —
   *  the social-growth line on the exported card, NOT a truncated insight. */
  shareLines: Record<string, LocalizedString>;
}

/**
 * A `multi`-type module read in `solo` mode → a single-subject "signs present" COUNT
 * about ONE person, tiered by signal share (see scoreCount + generateCountResult).
 * Distinct from MultiResults: `{name}` is the SUBJECT being described, NEVER a contest
 * winner ("{name} loves you the most").
 */
export type CountTier = 'none' | 'low' | 'medium' | 'high';

export interface CountResults {
  /** Descriptive (not name-first winner) headline per tier; `{name}` = the one person,
   *  filled via localizeTemplate. Tiers by share: none <= 0.1, low < 0.4, medium < 0.7,
   *  high otherwise. */
  tiers: Record<CountTier, LocalizedString>;
  /** One share-card quote per tier. */
  shareLines: Record<CountTier, LocalizedString>;
  /** Insight pool keyed by TIER (>= 6 per tier; 3 picked per reading). Tier-keyed so a
   *  low/zero read never draws affirming copy — NOT dimension-keyed. */
  insights: Record<CountTier, LocalizedString[]>;
}

export interface SoloResults {
  verdicts: {
    positive: LocalizedString;
    neutral: LocalizedString;
    negative: LocalizedString;
  };
  /** Short headline word shown as the big result title (e.g. "Secure"). */
  verdictLabel: {
    positive: LocalizedString;
    neutral: LocalizedString;
    negative: LocalizedString;
  };
  whatThisMeans: {
    positive: LocalizedString;
    neutral: LocalizedString;
    negative: LocalizedString;
  };
  /** One designed share-card quote per verdict — first-person confession voice
   *  (the self-module card is the user talking about themselves). */
  shareLines: {
    positive: LocalizedString;
    neutral: LocalizedString;
    negative: LocalizedString;
  };
  insights: Record<string, LocalizedString[]>;
}

/**
 * Results for `categorical` solo modules (aura_color; attachment_style once converted).
 *
 * Rendering contract (result screen):
 *   - Reveal name  = categories[dominantDimension].label      (e.g. "Violet")
 *   - Verdict line = categories[dominantDimension].verdict, and when
 *     secondaryDimension exists append edgeTemplate with {edge} replaced by
 *     categories[secondaryDimension].label  (→ "…with a Rose edge")
 *   - Body card    = whatThisMeans; bullets = 3 insights selected by
 *     selectInsights(insights, dominantDimension, seed) — pools are keyed by
 *     CATEGORY (the winning color), not by question dimension.
 *   - Share card   = shareLine (first-person confession voice, per solo rules)
 */
export interface CategoricalResults {
  categories: Record<
    string,
    {
      /** Short headline shown as the big Playfair reveal (e.g. "Violet"). */
      label: LocalizedString;
      /** Full verdict statement ("Your aura glows violet."). */
      verdict: LocalizedString;
      /** "What this means" body copy. */
      whatThisMeans: LocalizedString;
      /** Share-card quote — first-person confession voice. */
      shareLine: LocalizedString;
    }
  >;
  /** Runner-up phrase; {edge} is replaced with the secondary category's label. */
  edgeTemplate: LocalizedString;
  /** 6 insight variants per category — selected by winning category. */
  insights: Record<string, LocalizedString[]>;
}
